language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install --upgrade importlib-metadata; pip3 install .

# commands to run tes
# before_script: redis-cli ping

script:
  - python3.7 -m unittest discover

after_success:
#  - codecov

services:
#  - redis-server