language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install --upgrade importlib-metadata
  - pip3 install .
  - pip3 install pynndescent==0.5.7
  - pip3 install faiss-cpu==1.6.5 --no-cache

# commands to run tes
# before_script: redis-cli ping

script:
  - python3.7 -m unittest discover

after_success:
#  - codecov

services:
#  - redis-server